# Generated by Django 5.0.4 on 2024-04-29 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='units_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('mm', 'Millimeter'), ('inch', 'Inch'), ('m', 'Meter'), ('ft', 'Foot'), ('cm', 'Centimeter')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='opening_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantity', models.IntegerField()),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bloq.units_model')),
            ],
        ),
        migrations.CreateModel(
            name='door_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantity', models.IntegerField()),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bloq.units_model')),
            ],
        ),
        migrations.CreateModel(
            name='block_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('layer', models.CharField(max_length=100)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bloq.units_model')),
            ],
        ),
        migrations.CreateModel(
            name='window_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantity', models.IntegerField()),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bloq.units_model')),
            ],
        ),
    ]
