# Generated by Django 5.0.4 on 2024-04-29 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloq', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opening_model',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='block_model',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='window_model',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='door_model',
            name='unit',
        ),
        migrations.DeleteModel(
            name='units_model',
        ),
    ]
